+incdir+../
/data/home/harhen/Desktop/GC_DRAM_FINAL_PROJECT/controller_advanced_refresh/MEMOREY_WRAPER_FULL_TB.sv
../MUX_8:3.sv
../DFF.sv
../DECODER_3:8.sv
../CONTROLLER.sv
../128x64_DRAM.sv
../CYCLES_COUNTER.sv
../MEM_ADDR_COUNTER.sv
../MUX_2:1.sv
../MEMOREY_WRAPER.sv
../SR.sv
