+incdir+../
/data/home/harhen/Desktop/GC_DRAM_FINAL_PROJECT/controller_advanced_refresh/TB.sv
../TOP.sv
../SAT.sv
../REF_MEM_COUNTER.sv
../CYCLES_COUNTER.sv
../MUX_8:3.sv
../POSEDGE_DETECTOR.sv
../DFF.sv
../DECODER_3:8.sv
../CONTROLLER.sv
../128x64_DRAM.sv
../CYCLES_COUNTER.sv
../MUX_2:1.sv
../MEMOREY_WRAPER.sv
../SR.sv
